### ISSUE TITLE
dose it have any plan to support CDC/NCM?

### ISSUE THREAD

**Issue by fusigi0930** [f-secure-foundry/imx-usbnet#1]
I am trying to porting cdc/ncm to usbnet, but I cannot pass data while UBS_CDC_GET_NTB_PARAMETERS.
do you have any plan to support CDC/NCM?

**Comment by abarisani** [comment]
We have no plans at this time to support CDC/NCM, if you ever get around it I'd be happy to review and merge a Pull Request. Kind regards.
